services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  api-gateway:
    build: ./RestaurantManager
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - order-service
      - kitchen-service
      - payment-service

  order-service:
    build: 
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - DB_CONNECTION_STRING=Host=order-db;Port=5432;Username=postgres;Password=postgres;Database=orderdb
    depends_on:
      - order-db

  kitchen-service:
    build: 
      context: .
      dockerfile: KitchenService/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - DB_CONNECTION_STRING=Host=kitchen-db;Port=5432;Username=postgres;Password=postgres;Database=kitchendb
    depends_on:
      - kitchen-db
      - kafka

  payment-service:
    build: 
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://+:5004
      - DB_CONNECTION_STRING=Host=payment-db;Port=5432;Username=postgres;Password=postgres;Database=paymentdb
    depends_on:
      - payment-db
      - kafka

  order-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - backend

  kitchen-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kitchendb
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data
    networks:
      - backend

  payment-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  order-db-data:
  kitchen-db-data:
  payment-db-data:

networks:
  backend:
    driver: bridge
